# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kofero' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kofero
  pod 'presenter', :path => '../presenter'
  pod 'SwiftyJSON', '~> 4.3.0'
  pod 'NeedleFoundation'
  pod 'Google-Mobile-Ads-SDK', '~> 8.3.0'

end
