# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kofero' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kofero
  pod 'presenter', :path => '../presenter'
  pod 'SwiftyJSON'
  pod 'NeedleFoundation'
  pod 'Google-Mobile-Ads-SDK', '~> 11.0.0'

# Add the Firebase pod for Google Analytics
pod 'FirebaseAnalytics'
pod 'FirebaseCrashlytics'

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
            end
        end
    end
end

end
